FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java17 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /code/src
ARG QUARKUS_PROFILE
ARG APP_NAME
RUN ./mvnw package -DskipTests  -Dquarkus.application.name=atm-layer-model -Dquarkus.profile=integration

## Stage 2 : create the docker final image
FROM amazoncorretto:17.0.8-alpine3.18@sha256:34650d7c653af234dad21cd2d89d2f0dbdb1bad54041014932e51b3492e0dec5
WORKDIR /work
COPY --from=build /code/target /work

EXPOSE 8086

# Comando per avviare l'applicativo Quarkus quando il contenitore viene eseguito
CMD ["java", "-jar", "quarkus-app/quarkus-run.jar"]
