version: '3'

services:
  quarkus-app:
    container_name: quarkus
    networks:
      customnetwork:
        ipv4_address: 172.100.0.10
    build:
      context: ../
      dockerfile: ./integration-test/Dockerfile-quarkus

    ports:
      - "8086:8080"

  postgres:
    image: postgres:latest
    container_name: postgres_integration
    networks:
      customnetwork:
        ipv4_address: 172.100.0.11
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5434:5432"
  minio:
    image: minio/minio
    container_name: minio
    networks:
      customnetwork:
        ipv4_address: 172.100.0.12
    ports:
      - "9100:9000"
      - "9110:9001"
    environment:
      MINIO_ACCESS_KEY: key
      MINIO_SECRET_KEY: password
    command: server /data --console-address ":9001"
  createbuckets:
    image: minio/mc
    networks:
      customnetwork:
        ipv4_address: 172.100.0.13
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 key password;
      /usr/bin/mc mb myminio/bucket;
      /usr/bin/mc policy set public myminio/bucket;
      exit 0;
      "
  mockoon:
    container_name: mockoon
    ports:
      - "3000:3000"
    networks:
      customnetwork:
        ipv4_address: 172.100.0.14
    build:
      context: ../
      dockerfile: ./integration-test/Dockerfile-mockoon

  postman-runner:
    networks:
      customnetwork:
        ipv4_address: 172.100.0.15
    build:
      context: ../
      dockerfile: ./integration-test/Dockerfile-postman
    volumes:
      - ./output:/output
    depends_on:
      - quarkus-app
      - postgres
      - minio
      - mockoon
networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.100.0.0/16