microservice-chart:
  namespace: "receipts"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-receipt-pdf-service
    tag: "0.7.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 8080 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 8080 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuuat.receipts.internal.uat.platform.pagopa.it"
    path: /pagopa-receipt-pdf-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 5
    pollingInterval: 10 # seconds
    cooldownPeriod: 120 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  fileConfig: {}
  envConfig:
    APP_NAME: "pdf-receipt-service"
    APP_ENVIRONMENT: "uat"
    WEBSITE_SITE_NAME: 'pagopareceiptpdfservice' # required to show cloud role name in application insights
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    COSMOS_RECEIPT_SERVICE_ENDPOINT: 'https://pagopa-u-weu-receipts-ds-cosmos-account.documents.azure.com:443/'
    COSMOS_RECEIPT_DB_NAME: 'db'
    COSMOS_RECEIPT_CONTAINER_NAME: 'receipts'
    BLOB_STORAGE_ACCOUNT_ENDPOINT: 'https://pagopauweureceiptsfnsa.blob.core.windows.net'
    BLOB_STORAGE_CONTAINER_NAME: 'pagopa-u-weu-receipts-azure-blob-receipt-st-attach'
    ENABLE_ECS_CONSOLE: "true"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopareceiptspdfserviceotl,deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    JAVA_TOOL_OPTIONS: "-javaagent:/deployments/jmx_prometheus_javaagent-0.19.0.jar=12345:/deployments/config.yaml -javaagent:/deployments/opentelemetry-javaagent.jar -Xmx1024m"
  envFieldRef:
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-u-connection-string'
    COSMOS_RECEIPT_KEY: "cosmos-receipt-pkey"
    BLOB_STORAGE_CONN_STRING: "receipts-storage-account-connection-string"
    COSMOS_RECEIPTS_CONN_STRING: "cosmos-receipt-connection-string"
    OTEL_EXPORTER_OTLP_HEADERS: 'elastic-otl-secret-token'
  keyvault:
    name: "pagopa-u-receipts-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: true
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-receipt-pdf-service
        tag: "0.7.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
